apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gb2a7f0p1-java-quarkus
  janus-idp.io/tekton: gb2a7f0p1-java-quarkus
  backstage.io/kubernetes-id: gb2a7f0p1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gb2a7f0p1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
